# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# Code generation dependencies
required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
]

[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "~1.0.0"

[[constraint]]
  name = "gopkg.in/ini.v1"
  version = "~1.28.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "7f97868eec74b32b0982dd158a51a446d1da7eb5"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.0"

[[constraint]]
  branch = "master"
  name = "k8s.io/utils"

[[constraint]]
  branch = "master"
  name = "github.com/heptiolabs/healthcheck"

[[constraint]]
  name = "github.com/coreos/go-semver"
  revision = "e214231b295a8ea9479f11b70b35d5acf3556d9b"

# gengo needs to be manually pinned to the version listed in code-generators
# Gopkg.toml, because the k8s project does not produce Gopkg.toml files & dep
# does not parse the Godeps.json file to determine revisions to use.
[[override]]
  name = "k8s.io/gengo"
  revision = "b6c426f7730e6d66e6e476a85d1c3eb7633880e0"

[[constraint]]
  name = "github.com/robfig/cron"
  revision = "df38d32658d8788cd446ba74db4bb5375c4b0cb3"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.41"
