---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlclusters.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Cluster
    singular: mysqlcluster
    plural: mysqlclusters
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackups.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Backup
    singular: mysqlbackup
    plural: mysqlbackups
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlrestores.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Restore
    singular: mysqlrestore
    plural: mysqlrestores
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackupschedules.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: BackupSchedule
    singular: mysqlbackupschedule
    plural: mysqlbackupschedules
